-- ~/.config/hypr/hyprland.lua
-- Hyprland Lua entrypoint

local home = os.getenv("HOME")

package.path =
  home .. "/.config/hypr/configs/?.lua;" ..
  home .. "/.config/hypr/UserConfigs/?.lua;" ..
  home .. "/.config/hypr/animations/?.lua;" ..
  home .. "/.config/hypr/Monitor_Profiles/?.lua;" ..
  home .. "/.config/hypr/wallust/?.lua;" ..
  package.path

_G.configs = home .. "/.config/hypr/configs"
_G.UserConfigs = home .. "/.config/hypr/UserConfigs"

_G.surface_lowest = "rgba(111111ee)"
_G.primary = "rgba(89b4faee)"
_G.secondary = "rgba(cba6f7ee)"
_G.tertiary = "rgba(f5c2eeee)"
_G.surface = "rgba(1e1e2eee)"
_G.error = "rgba(f38ba8ee)"

hl.config({
  autogenerated = false,
})

-- Emergency survival basics FIRST.
-- hl.monitor({
--  output = "desc:Acer Technologies KG271U N3 1322131231233",
--  mode = "2560x1440@180.0",
--  position = "1x2000",
--  scale = 1.0,
-- })

-- hl.bind("SUPER + RETURN", hl.dsp.exec_cmd("kitty"))
-- hl.bind("SUPER + M", hl.dsp.exit())
-- hl.bind("CTRL + ALT + BACKSPACE", hl.dsp.exit())
-- hl.bind("SUPER + B", hl.dsp.exec_cmd("brave"))

-- hl.on("hyprland.start", function()
--  hl.exec_cmd("kitty")
-- end)

-- Load converted stack AFTER survival basics.
require("01-UserDefaults")

require("ENVariables")
require("Startup_Apps")

-- Leave laptop files disabled unless they exist and are converted.
-- require("Laptops")
-- require("LaptopDisplay")

require("SystemSettings")
require("UserSettings")

require("wallust-hyprland")
require("UserDecorations")

-- Load only if the file exists.
require("00-default")
require("UserAnimations")



require("WindowRules")
--require("UserWindowRules")

require("Keybinds")
require("UserKeybinds")
require("UserStartup_Apps")
require("monitors")
require("workspaces")
require("RainbowBorderColor")


-- This loads Noctalia-generated Hyprland colors.

-- This loads Noctalia-generated Hyprland colors.
dofile("/home/zer0/.config/hypr/noctalia/noctalia-colors.lua")
