general {
    ignore_dbus_inhibit = false
}

listener {
    timeout = 900
    on-timeout = notify-send "You Are Going Idle" "Fuckface"
}

# Shutdown 30 mins after screen turned off if completely idle
listener {
    timeout = 5400                          # hour and a half total idle (30 minutes after DPMS off)
    on-timeout = systemctl poweroff	    # Command to shut down
}

