local hl = require("hyprland")
local home = os.getenv("HOME")

package.path = home .. "/.config/hypr/?.lua;"
  .. home .. "/.config/hypr/?/init.lua;"
  .. package.path

_G.configs = home .. "/.config/hypr/configs"
_G.UserConfigs = home .. "/.config/hypr/UserConfigs"

_G.surface_lowest = "rgba(111111ee)"
_G.primary = "rgba(89b4faee)"
_G.secondary = "rgba(cba6f7ee)"
_G.tertiary = "rgba(f5c2eeee)"
_G.surface = "rgba(1e1e2eee)"
_G.error = "rgba(f38ba8ee)"

hl.config({
  autogenerated = false,
})

-- Defaults must load before keybinds/scripts that use _G.term, _G.files, etc.
require("UserConfigs.01-UserDefaults")

require("configs.ENVariables")
require("UserConfigs.ENVariables")

require("configs.Startup_Apps")
require("UserConfigs.Startup_Apps")

require("configs.Laptops")
require("UserConfigs.Laptops")
require("UserConfigs.LaptopDisplay")

require("configs.SystemSettings")

require("UserConfigs.UserDecorations")
require("UserConfigs.UserAnimations")
require("UserConfigs.UserSettings")

require("configs.WindowRules")
require("UserConfigs.WindowRules")

require("configs.Keybinds")
require("UserConfigs.UserKeybinds")

require("monitors")
require("workspaces")

require("noctalia.HVE.overlay")