-- Generated by nwg-displays on 2026-05-19 at 21:00:27. Do not edit manually.

hl.monitor({
    output = "desc:Acer Technologies KG271U N3 1322131231233",
    mode = "2560x1440@180.0",
    position = "0x2000",
    scale = 1.0
})
hl.monitor({
    output = "desc:Sceptre Tech Inc Sceptre O34",
    mode = "3440x1440@165.0",
    position = "2560x0",
    scale = 1.0,
    transform = 3
})
