# Commands and Apps to be executed at launch

# exec-once = sleep 5 && trcc gui
exec-once = lact gui --startminimized
# exec-once = sleep 5 && trcc gui theme-load "Custom_zer0"

exec-once = openrgb --profile "helldivers"
exec-once = sleep 5 && trcc gui
