# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates


windowrule {
    name = steam-panel
    match:class = ^(steam)$
    match:title = ^(Steam)$

    workspace = 5 silent
    float = true
    size = 1100 750
    move = (monitor_w-1100-12) (monitor_h-750-15)
}

windowrule {
    name = steam-games
    match:class = ^(steam_app_.*)$

    workspace = 4
}

windowrule {
    name = gamescope-games
    match:class = ^(gamescope)$

    workspace = 4
}

